### PR TITLE
cp1616: don't link yaml-cpp without searching for it

### PR DESCRIPTION
**Pull request by gavanderhoorn**
As per subject.

Tested on a Precise/Hydro and a Trusty/Indigo installation.

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
The `HAVE_NEW_YAMLCPP` define is currently not used anywhere, but I've left it in, in case you'd want to do some conditional compilation of yaml-cpp interfacing code.

**Comment by durovsky** [comment]
It looks sophisticated Gijs, I just don't understand how did you make it to work with both Hydro and Indigo? I have rewritten the code to new yaml cpp API. How did you even test it with Hydro? Is is even possible to use it with Hydro now when code has been modified?  Did you use some older commit?

Sorry I m just little lost now with this Hydro and Indigo thing :)

**Comment by gavanderhoorn** [comment]
It's not really so difficult: it just uses `pkg-config` to look for an installation of `yaml-cpp`. Only thing is that `yaml-cpp_LIBRARIES` does not contain absolute paths, and CMake prefers those. So we use `find_library(..)` (using the `_LIBRARY_PATHS` as a search base) to find the actual path to the library.

The `HAVE_NEW_YAMLCPP` is just a define that gets set whenever the version of the discovered `yaml-cpp` is at least 0.5, which is when the API breaking changes were introduced. If you so desire, you could use that to add some `#ifdef`s to your code that would conditionally use either the old or the new API.

In this case you don't do that, but I thought to include it anyway.

> How did you even test it with Hydro? Is is even possible to use it with Hydro now when code has been modified? Did you use some older commit?

I only tested the detection code, _not_ the actual nodes. With a normal 'Hydro install' you'd get `yaml-cpp < 0.5`, so your new nodes cannot even be compiled there. Were I to provide a 0.5 version of `yaml-cpp` to the `CMakeLists.txt` of `siemens_cp1616` on a Hydro installation, it should pick that up and compile.

As Hydro is EOL, I don't know how much sense it makes to spend time getting everything to work there, but it is certainly possible.

**Comment by gavanderhoorn** [comment]
I've rebased these changes on top of your current `indigo_devel`.

**Comment by durovsky** [comment]
Thanks for explanation, now I understand how you meant that.... Even if Hydro is EOL, I will use `#ifdef`s to add old API function to current code, at least it will be a nice comparison

**Pull request merged**
